/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControladorInventario;
import control.ControladorPelicula;
import control.ControladorTienda;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Inventario;
import modelo.Pelicula;
import modelo.Tienda;

/**
 *
 * @author user
 */
public class VListaInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form VListaInventario
     */
    public VListaInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTienda = new javax.swing.JLabel();
        jcTienda = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Inventario");

        jlTienda.setText("Tienda ID:");

        jcTienda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todo" }));
        cargarTiendasCombo();
        jcTienda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcTiendaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jlTienda)
                .addGap(74, 74, 74)
                .addComponent(jcTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTienda)
                    .addComponent(jcTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Pelicula ", "Tienda ID","Disponible"
            }
        ));
        cargarInventarios("0");
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcTiendaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcTiendaItemStateChanged
        // TODO add your handling code here:
        if(jcTienda.getSelectedItem().toString().equalsIgnoreCase("Todo")){
            cargarInventarios("0");
        }else{
        cargarInventarios(jcTienda.getSelectedItem().toString());}
        
        
    }//GEN-LAST:event_jcTiendaItemStateChanged
       private void cargarTiendasCombo(){
         ArrayList<Tienda> listaTiendas = new ArrayList();
          listaTiendas=ControladorTienda.listadoTiendas("0");
                    
          for(int i=0;i<listaTiendas.size();i++){
              jcTienda.addItem(listaTiendas.get(i).getID());
                            
          }
       }      

    private void cargarInventarios(String c){    
        //traer el listado de peliculas  
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) jTable1.getModel();
        ArrayList<Inventario> listadoInventario = new ArrayList();        
        listadoInventario = ControladorInventario.listadoInventariosTienda(c);  
        limpiarTabla();
        String titulo;
        for(int i= 0; i < listadoInventario.size(); i++){  
              //titulo=nombrePeliculas(listadoInventario.get(i).getPeliculaID()+"");
              modelo.addRow(new Object[]{
              listadoInventario.get(i).getID(),
              nombrePeliculas(listadoInventario.get(i).getPeliculaID()+""),
              listadoInventario.get(i).getTiendaID(),
              listadoInventario.get(i).getDisponible()
              });
              
             
        }
    }
    private void limpiarTabla(){
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) jTable1.getModel();
        for(int i=modelo.getRowCount()-1; i>=0 ; i--){
            modelo.removeRow(i);
        }
    }
    
    public String nombrePeliculas(String c){
        ArrayList<Pelicula> listadoPeliculas = new ArrayList();        
        listadoPeliculas = ControladorPelicula.listadoPeliculas(c);  
        
        
        return listadoPeliculas.get(0).getTitulo();
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jcTienda;
    private javax.swing.JLabel jlTienda;
    // End of variables declaration//GEN-END:variables
}
