/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControladorCategoria;
import control.ControladorLenguaje;
import control.ControladorPelicula;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Categoria;
import modelo.Lenguaje;
import modelo.Pelicula;

/**
 *
 * @author user
 */
public class VModificarPeliculas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaGenerada
     */
    public VModificarPeliculas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jlID = new javax.swing.JLabel();
        jlDescripcion = new javax.swing.JLabel();
        jlAño = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTasa = new javax.swing.JTextField();
        jlLenguaje = new javax.swing.JLabel();
        jcLenguaje = new javax.swing.JComboBox();
        jlAlquiler = new javax.swing.JLabel();
        jcDuracion = new javax.swing.JComboBox();
        jlTamaño = new javax.swing.JLabel();
        jlCosto = new javax.swing.JLabel();
        jlClasificacion = new javax.swing.JLabel();
        jlEspecial = new javax.swing.JLabel();
        jlText = new javax.swing.JLabel();
        txtTamaño = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtClasificacion = new javax.swing.JTextField();
        txtEspecial = new javax.swing.JTextField();
        txtFull = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jcCategorias = new javax.swing.JComboBox();
        txtCategorias = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbNuevo = new javax.swing.JButton();
        jbRegistrar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Peliculas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion Peliculas:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jlTitulo.setText("Titulo:");

        jlID.setText("ID:");

        jlDescripcion.setText("Descripcion:");

        jlAño.setText("Año:");

        txtTitulo.setEnabled(false);
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtID.setEnabled(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        txtDescripcion.setEnabled(false);

        txtAño.setEnabled(false);

        jLabel5.setText("Tasa Alquiler:");

        txtTasa.setEnabled(false);

        jlLenguaje.setText("Lenguaje:");

        jcLenguaje.setEnabled(false);
        jcLenguaje.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar" }));
        cargarLenguajesCombo();

        jlAlquiler.setText("Duracion Alquiler:");

        jcDuracion.setEnabled(false);
        jcDuracion.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"seleccionar", "1", "2", "3", "4","5","6","7" }));
        jcDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcDuracionActionPerformed(evt);
            }
        });

        jlTamaño.setText("Tamaño:");

        jlCosto.setText("Costo Reposicion:");

        jlClasificacion.setText("Clasificacion:");

        jlEspecial.setText("Presentacion Especial:");

        jlText.setText("FullText:");

        txtTamaño.setEnabled(false);

        txtCosto.setEnabled(false);

        txtClasificacion.setEnabled(false);

        txtEspecial.setEnabled(false);

        txtFull.setEnabled(false);

        jLabel1.setText("Categoria:");

        jcCategorias.setEnabled(false);
        jcCategorias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar" }));
        cargarCategoriasCombo();
        jcCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCategoriasActionPerformed(evt);
            }
        });

        txtCategorias.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTitulo)
                            .addComponent(jlID)
                            .addComponent(jlDescripcion)
                            .addComponent(jlAño))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescripcion)
                            .addComponent(txtID)
                            .addComponent(txtTitulo)
                            .addComponent(txtAño, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcLenguaje, javax.swing.GroupLayout.Alignment.TRAILING, 0, 100, Short.MAX_VALUE))
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlLenguaje)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlAlquiler)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlEspecial)
                            .addComponent(jlTamaño)
                            .addComponent(jlCosto)
                            .addComponent(jlClasificacion)
                            .addComponent(jlText)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCosto)
                            .addComponent(txtClasificacion)
                            .addComponent(txtEspecial)
                            .addComponent(txtFull, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txtTamaño)
                            .addComponent(jcCategorias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txtCategorias))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTitulo)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTamaño)
                    .addComponent(txtTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCosto)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlClasificacion)
                    .addComponent(txtClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAño, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlAño)
                        .addComponent(jlEspecial)
                        .addComponent(txtEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlText)
                        .addComponent(txtFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlLenguaje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlAlquiler)
                            .addComponent(jcDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controles:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbRegistrar.setEnabled(false);
        jbRegistrar.setText("Registrar");
        jbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarActionPerformed(evt);
            }
        });

        jbBorrar.setText("Borrar");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbCancelar.setEnabled(false);
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]{
            },
            new String [] {
                "ID", "Titulo", "Descripcion", "Año","Lenguaje","DuracionRenta",
                "TasaAlquiler","Tamaño","Costo","Clasificacion","ActuacionEspecial","FullText"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false,false,false,false,
                false, false,false,false,false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cargarPeliculas("0");
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void jcCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcCategoriasActionPerformed

    private void jcDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcDuracionActionPerformed
     
    }//GEN-LAST:event_jcDuracionActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()==-1){
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"No hay registros");
            }
            else{
                JOptionPane.showMessageDialog(this,"Seleccione una fila");
            }
        }else {
                                  
            txtID.setText(modelo.getValueAt(
                    jTable1.getSelectedRow(), 0).toString());            
            txtTitulo.setText(modelo.getValueAt(
                    jTable1.getSelectedRow(), 1).toString());
            txtDescripcion.setText(modelo.getValueAt(
                    jTable1.getSelectedRow(), 2).toString());  
            txtAño.setText(modelo.getValueAt(
                    jTable1.getSelectedRow(), 3).toString());
            jcLenguaje.setSelectedIndex(Integer.parseInt(modelo.getValueAt(jTable1.getSelectedRow(),4).toString()));
            jcDuracion.setSelectedItem(modelo.getValueAt(jTable1.getSelectedRow(),5).toString());
            txtTasa.setText(modelo.getValueAt(jTable1.getSelectedRow(),6).toString());
            txtTamaño.setText(modelo.getValueAt(jTable1.getSelectedRow(),7).toString());
            txtCosto.setText(modelo.getValueAt(jTable1.getSelectedRow(),8).toString());
            //txtClasificacion.setText(modelo.getValueAt(jTable1.getSelectedRow(),9).toString());
//            txtEspecial.setText(modelo.getValueAt(jTable1.getSelectedRow(),10).toString());
            txtFull.setText(modelo.getValueAt(jTable1.getSelectedRow(),11).toString());
            
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:        
        txtID.setText("");            
        txtTitulo.setText("");
        txtDescripcion.setText("");  
        txtAño.setText("");
        jcLenguaje.setSelectedIndex(0);
        jcDuracion.setSelectedIndex(0);
        txtTasa.setText("");
        txtTamaño.setText("");
        txtCosto.setText("");
        txtClasificacion.setText("");
        txtEspecial.setText("");
        txtFull.setText("");
        
        if(jbNuevo.getText().equals("Nuevo")){
            jbRegistrar.setEnabled(true);
            txtID.setEnabled(true);
            txtTitulo.setEnabled(true);
            txtDescripcion.setEnabled(true);
            txtAño.setEnabled(true);
            jcLenguaje.setEnabled(true);
            jcDuracion.setEnabled(true);
            txtTasa.setEnabled(true);
            txtTamaño.setEnabled(true);
            txtCosto.setEnabled(true);
            //txtClasificacion.setEnabled(true);
            //txtEspecial.setEnabled(true);
            //txtFull.setEnabled(true);
            jbModificar.setEnabled(false);
            jbNuevo.setText("Cancelar");
            jbBorrar.setEnabled(false);
            jTable1.setEnabled(false);
            jTable1.setVisible(false);
            txtID.requestFocusInWindow();
        }
        else{
            jbRegistrar.setEnabled(false);
            txtID.setEnabled(false);
            txtTitulo.setEnabled(false);
            txtDescripcion.setEnabled(false);
            txtAño.setEnabled(false);           
            jcLenguaje.setEnabled(false); 
            jcDuracion.setEnabled(false);
            txtTasa.setEnabled(false);
            txtTamaño.setEnabled(false);
            txtCosto.setEnabled(false);
            txtClasificacion.setEnabled(false);
            txtEspecial.setEnabled(false);
            txtFull.setEnabled(false);
            jbNuevo.setText("Nuevo");
            jbModificar.setEnabled(true);
            jbBorrar.setEnabled(true);
            jTable1.setEnabled(true);
            jTable1.setVisible(true);
            jbNuevo.requestFocusInWindow();
        }
        
        
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarActionPerformed
        // TODO add your handling code here:
        if(txtID.getText().trim().equals(""))
            JOptionPane.showMessageDialog(this,"Ingrese el ID de la Pelicula");
        else{
            if (jcLenguaje.getSelectedItem().toString().trim().
                    equals("Seleccionar") || jcDuracion.getSelectedItem().toString().trim().equals("seleccionar")){
                JOptionPane.showMessageDialog(this,"Seleccione Duracion alquilers y lenguaje ");
                jcLenguaje.requestFocusInWindow(); }               
            else {
                Pelicula pelicula = new Pelicula();
                pelicula.setID(Integer.parseInt(txtID.getText()));
                pelicula.setTitulo(txtTitulo.getText());
                pelicula.setDescripcion(txtDescripcion.getText());
                pelicula.setAño(Integer.parseInt(txtAño.getText()));
                pelicula.setLenguaje(jcLenguaje.getSelectedIndex());
                pelicula.setDuracionRenta(Integer.parseInt(jcDuracion.getSelectedItem().toString()));
                pelicula.setTasa(Double.parseDouble(txtTasa.getText()));
                pelicula.setTamaño(Integer.parseInt(txtTamaño.getText()));
                pelicula.setCosto(Double.parseDouble(txtCosto.getText()));
                pelicula.setRating(txtClasificacion.getText());
                pelicula.setEspecial(txtEspecial.getText());
                pelicula.setFulltex(txtFull.getText());
                
                int tamaño;
                tamaño=ControladorPelicula.listadoCategoriasP(pelicula.getID()+"").size();
                
                if(tamaño==0){
                int resultado = 0;
                    resultado = ControladorPelicula.grabarPelicula(pelicula);
                    if(resultado == 1){
                        JOptionPane.showMessageDialog(this,
                                "Registro Grabado con éxito",
                                "Confirmación",JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Error al grabar",
                                "Confirmación",JOptionPane.ERROR_MESSAGE);
                    }

                    cargarPeliculas("0");

            jbRegistrar.setEnabled(false);
            txtID.setEnabled(false);
            txtTitulo.setEnabled(false);
            txtDescripcion.setEnabled(false);
            txtAño.setEnabled(false);           
            jcLenguaje.setEnabled(false); 
            jcDuracion.setEnabled(false);
            txtTasa.setEnabled(false);
            txtTamaño.setEnabled(false);
            txtCosto.setEnabled(false);
            txtClasificacion.setEnabled(false);
            txtEspecial.setEnabled(false);
            txtFull.setEnabled(false);
            jbNuevo.setText("Nuevo");
            jbModificar.setEnabled(true);
            jbBorrar.setEnabled(true);
            jTable1.setEnabled(true);
            jTable1.setVisible(true);
            jbNuevo.requestFocusInWindow();
                                       
            }else{
                   JOptionPane.showMessageDialog(this,
                           "IDya registrado","Confirmación",
                           JOptionPane.ERROR_MESSAGE); 
                   txtID.requestFocusInWindow();
                }
                
          
            }
        }
        
        
        
        
    }//GEN-LAST:event_jbRegistrarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        // TODO add your handling code here:
        if(txtID.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, 
                    "Por favor seleccione una Pelicula","Error", 
                    JOptionPane.ERROR_MESSAGE);
        }else{
            int respuesta = JOptionPane.showConfirmDialog(this,
                    "¿Desea Eliminar la pelicula con el codigo : " +
                            txtID.getText().trim()+
                    " ?", "Confirmación de Acción", JOptionPane.YES_NO_OPTION);
            if(respuesta == JOptionPane.YES_OPTION){
                String codigo = "";
                codigo  = txtID.getText().trim();
                
                if(ControladorPelicula.borrarPelicula(codigo) == 1){
                    JOptionPane.showMessageDialog(this, 
                            "Registro Borrado con éxtio", 
                            "Confirmación de acción", 
                            JOptionPane.INFORMATION_MESSAGE);                    
                    cargarPeliculas("0");
                }
                else{
                    JOptionPane.showMessageDialog(this, 
                            "Error al borrar", "Confirmación de acción", 
                            JOptionPane.ERROR_MESSAGE);                    
                }
            }
        }
                
        
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        if(jbModificar.getText().equalsIgnoreCase("Modificar")){
            if(jTable1.getSelectedRow() == -1){
               if(jTable1.getRowCount() == 0){
                   JOptionPane.showMessageDialog(this,"No hay registros");
               }else{
                   JOptionPane.showMessageDialog(this,"Seleccione una fila");
               }
            }else{    
                
            jbRegistrar.setEnabled(true);            
            txtTitulo.setEnabled(true);
            txtDescripcion.setEnabled(true);
            txtAño.setEnabled(true);
            jcLenguaje.setEnabled(true);
            jcDuracion.setEnabled(true);
            txtTasa.setEnabled(true);
            txtTamaño.setEnabled(true);
            txtCosto.setEnabled(true);
            //txtClasificacion.setEnabled(true);
            //txtEspecial.setEnabled(true);
            //txtFull.setEnabled(true);            
            jbModificar.setText("Actualizar");
            jbBorrar.setEnabled(false);            
            jbCancelar.setEnabled(true);
           
             }
        }else {
            
            jbRegistrar.setEnabled(false);
            
            txtTitulo.setEnabled(false);
            txtDescripcion.setEnabled(false);
            txtAño.setEnabled(false);           
            jcLenguaje.setEnabled(false); 
            jcDuracion.setEnabled(false);
            txtTasa.setEnabled(false);
            txtTamaño.setEnabled(false);
            txtCosto.setEnabled(false);
            txtClasificacion.setEnabled(false);
            txtEspecial.setEnabled(false);
            txtFull.setEnabled(false);
            jbModificar.setText("Modificar");
            jbModificar.setEnabled(true);
            jbBorrar.setEnabled(true);                                 
            jbCancelar.setEnabled(false);
            jTable1.setEnabled(true);
             
            //Se crea el objeto Programa 
             Pelicula pelicula = new Pelicula();
             
             //Se configura los datos en el objeto programa de la clase
             //Programa
             pelicula.setID(Integer.parseInt(txtID.getText()));
             pelicula.setTitulo(txtTitulo.getText());                                          
             pelicula.setDescripcion(txtDescripcion.getText());                                          
             pelicula.setAño(Integer.parseInt(txtAño.getText())); 
             pelicula.setLenguaje(jcLenguaje.getSelectedIndex());
             pelicula.setDuracionRenta(Integer.parseInt(jcDuracion.getSelectedItem().toString()));
             pelicula.setTamaño(Integer.parseInt(txtTamaño.getText()));
             pelicula.setTasa(Double.parseDouble(txtTasa.getText()));
             
             
                         
             if(ControladorPelicula.modificarPelicula(pelicula) == 1){
                 JOptionPane.showMessageDialog(this,"Actualización exitosa");
                 this.cargarPeliculas("0");
             } else {
                 JOptionPane.showMessageDialog(this,"Actualización Fallida");
             }
             
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        txtID.setEnabled(false);
        txtTitulo.setEnabled(false);
        txtDescripcion.setEnabled(false);
        txtAño.setEnabled(false);           
        jcLenguaje.setEnabled(false); 
        jcDuracion.setEnabled(false);
        txtTasa.setEnabled(false);
        txtTamaño.setEnabled(false);
        txtCosto.setEnabled(false);
        txtClasificacion.setEnabled(false);
        txtEspecial.setEnabled(false);
        txtFull.setEnabled(false);      
        jbBorrar.setEnabled(true);
        jbNuevo.setEnabled(true);
        jbRegistrar.setEnabled(false);
        jbModificar.setText("Modificar");
        jbCancelar.setEnabled(false);
        jTable1.setEnabled(true);
     
    }//GEN-LAST:event_jbCancelarActionPerformed
    private void cargarCategoriasCombo(){
         ArrayList<Categoria> listaCategorias = new ArrayList();
          listaCategorias=ControladorCategoria.listadoCategorias("0");
                    
          for(int i=0;i<listaCategorias.size();i++){
              jcCategorias.addItem(listaCategorias.get(i).getNombre());
                            
          }
    }
    private void cargarLenguajesCombo(){
         ArrayList<Lenguaje> listaLenguajes = new ArrayList();
          listaLenguajes=ControladorLenguaje.listadoLenguajes("0");
                    
          for(int i=0;i<listaLenguajes.size();i++){
              jcLenguaje.addItem(listaLenguajes.get(i).getNombre());
                            
          }
    }
    private void cargarPeliculas(String c){    
        //traer el listado de peliculas 
        DefaultTableModel modelo;
        modelo = (DefaultTableModel) jTable1.getModel();
        ArrayList<Pelicula> listadoPeliculas = new ArrayList();
        //p=new ArrayList();
        //p=Controlador.listadoPeliculas(c);
        listadoPeliculas = ControladorPelicula.listadoCategoriasP(c);  
       //recorrer el listado y llenar cada fila
        for(int i= 0; i < listadoPeliculas.size(); i++){                       
              modelo.addRow(new Object[]{
              listadoPeliculas.get(i).getID(),
              listadoPeliculas.get(i).getTitulo(),
              listadoPeliculas.get(i).getDescripcion(),
              listadoPeliculas.get(i).getAño(),
              listadoPeliculas.get(i).getLenguaje(),
              listadoPeliculas.get(i).getDuracionRenta(),
              listadoPeliculas.get(i).getTasa(),
              listadoPeliculas.get(i).getTamaño(),
              listadoPeliculas.get(i).getCosto(),
              listadoPeliculas.get(i).getRating(),
              listadoPeliculas.get(i).getEspecial(),
              listadoPeliculas.get(i).getFulltex()
                     
                      
              });
             
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JComboBox jcCategorias;
    private javax.swing.JComboBox jcDuracion;
    private javax.swing.JComboBox jcLenguaje;
    private javax.swing.JLabel jlAlquiler;
    private javax.swing.JLabel jlAño;
    private javax.swing.JLabel jlClasificacion;
    private javax.swing.JLabel jlCosto;
    private javax.swing.JLabel jlDescripcion;
    private javax.swing.JLabel jlEspecial;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlLenguaje;
    private javax.swing.JLabel jlTamaño;
    private javax.swing.JLabel jlText;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCategorias;
    private javax.swing.JTextField txtClasificacion;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtEspecial;
    private javax.swing.JTextField txtFull;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtTamaño;
    private javax.swing.JTextField txtTasa;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
