/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import control.ControladorInventario;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Inventario;

/**
 *
 * @author invitado
 */
public class VModificarInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form VModificarInventario
     */
    public VModificarInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbVerInventario = new javax.swing.JButton();
        jbActualizarInventario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setTitle("Gestion de inventario");

        jbVerInventario.setText("Ver inventario");
        jbVerInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVerInventarioActionPerformed(evt);
            }
        });

        jbActualizarInventario.setText("Actualizar Inventario");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Inventario_ID", "Pelicula_ID", "Tienda_ID "
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbVerInventario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jbActualizarInventario)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbVerInventario)
                    .addComponent(jbActualizarInventario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVerInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerInventarioActionPerformed

   jbCargarInventario();

        // TODO add your handling code here:
    }//GEN-LAST:event_jbVerInventarioActionPerformed

    private void jbCargarInventario (){
      DefaultTableModel modelo;
        modelo = (DefaultTableModel) jTable2.getModel();
        ArrayList <Inventario> listadoInventario =new ArrayList();
        listadoInventario=ControladorInventario.listadoInventario("0");
        for(int i= 0; i < listadoInventario.size(); i++){                       
              modelo.addRow(new Object[]{
              listadoInventario.get(i).getID(),
              listadoInventario.get(i).getPeliculaID(),
              listadoInventario.get(i).getTiendaID(),
          
              });
        }  
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbActualizarInventario;
    private javax.swing.JButton jbVerInventario;
    // End of variables declaration//GEN-END:variables
}
